import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
    id: {
        // App Name
        app_name: "LabView AI",
        
        // Navigation / Tabs
        nav_home: "Beranda",
        nav_history: "Riwayat",
        nav_trends: "Tren",
        nav_profile: "Profil",
        
        // Login Page
        login_title: "LabView AI",
        login_subtitle: "Platform Transformasi Medis",
        email_address: "Alamat Email",
        password: "Kata Sandi",
        reset: "Reset",
        authenticate: "Autentikasi",
        social_integration: "Integrasi Sosial",
        continue_with_google: "Lanjutkan dengan Google",
        unregistered: "BELUM TERDAFTAR?",
        register_now: "Daftar Sekarang",
        login_failed: "Login Gagal: Periksa kembali email dan password Anda.",
        google_login_failed: "Google Sign-In gagal: ",
        
        // Register Page
        join_labview: "Gabung LabView",
        establish_digital_identity: "Buat identitas digital Anda",
        health_profile: "Profil Kesehatan",
        personalize_metrics: "Personalisasikan metrik Anda",
        full_identity: "Identitas Lengkap",
        secret_code: "Kode Rahasia (Sandi)",
        continue_btn: "LANJUTKAN",
        biological_sex: "Jenis Kelamin Biologis",
        male: "Laki-laki",
        female: "Perempuan",
        primary_goal: "Tujuan Utama",
        monitor_health: "Pantau Kesehatan",
        manage_condition: "Kelola Kondisi",
        fitness_tracking: "Pelacakan Kebugaran",
        finalize_profile: "SELESAIKAN PROFIL",
        initializing: "MENGINISIALISASI...",
        quick_setup: "Pengaturan Cepat",
        import_google_profile: "Impor Profil Google",
        already_have_access: "SUDAH PUNYA AKSES?",
        login_here: "Login di Sini",
        registration_failed: "Pendaftaran Gagal: ",
        
        // Dashboard Page
        system_active: "Sistem Aktif",
        app_guide: "Panduan Aplikasi",
        tutorial_step_1_title: "Foto Laporan",
        tutorial_step_1_desc: "Potret kertas hasil lab Anda.",
        tutorial_step_2_title: "Pantau Skor",
        tutorial_step_2_desc: "Semakin tinggi angka semakin baik.",
        tutorial_step_3_title: "Ingat Obat",
        tutorial_step_3_desc: "Aplikasi menyala jika waktunya minum obat.",
        understood: "Dimengerti",
        system_health_index: "Indeks Kesehatan Sistem",
        no_data: "Tidak Ada Data",
        optimal: "Optimal",
        diagnostic_link: "Tautan Diagnostik",
        processed_files: "Memproses {count} dokumen",
        add_med: "Tambah Obat",
        scans_total: "Total Scan",
        blood_sugar: "Gula Darah",
        medical_schedule: "Jadwal Pengobatan",
        no_schedule_found: "Tidak Ada Jadwal",
        confirm_delete_med: "Hapus jadwal obat ini?",
        medication_alert: "Peringatan Obat!",
        time_to_take_med: "Waktunya minum obat:",
        i_have_taken_it: "SAYA SUDAH MINUM",
        recent_alerts: "Peringatan Terbaru",
        attention_required: "Perlu Perhatian",
        no_new_notifications: "Tidak Ada Notifikasi Baru",
        save_btn: "Simpan",
        
        // Detail Page
        decrypting_report: "Mendekripsi Laporan",
        ai_diagnostic: "Diagnostik AI",
        system_analytics: "ANALISIS SISTEM",
        optimal_condition: "Kondisi Optimal",
        optimal_condition_msg: "Semua hasil lab terpantau baik. Pertahankan gaya hidup sehat Anda!",
        needs_monitoring: "Perlu Pemantauan",
        needs_monitoring_msg: "Hasil sedikit di luar rentang. Cukup jaga pola makan dan istirahat yang cukup.",
        extra_attention: "Perlu Perhatian Ekstra",
        extra_attention_msg: "Beberapa hasil memerlukan konsultasi dokter. Tetap tenang, ini sebagai langkah pencegahan awal.",
        health_assistant: "Asisten Kesehatan",
        export_for_doctor: "Ekspor untuk Dokter",
        consult_telemed: "Konsultasi Telemedis",
        chat_welcome: "Halo user! Ada yang ingin ditanyakan tentang hasil lab ini?",
        ai_analyzing: "AI MENGANALISIS...",
        ask_lab_placeholder: "Tanya hasil lab...",
        ai_busy_error: "Maaf, koneksi AI sedang sibuk.",
        check_further: "Cek Lanjut",
        attention: "Perhatian",
        no_interpretation: "Tidak ada interpretasi dari model AI.",
        
        // History Page
        retrieving_archives: "MENGAMBIL ARSIP...",
        history_archive: "Arsip Riwayat",
        medical_records_timeline: "Linimasa Catatan Medis",
        search_placeholder: "Cari interpretasi atau tanggal...",
        no_archival_records_found: "Tidak Ada Catatan Arsip",
        all: "Semua",
        normal: "Normal",
        watch: "Pantau",
        alert: "Bahaya",
        
        // Trends Page
        accessing_database: "Mengakses Database...",
        health_intel: "Intel Kesehatan",
        analytics: "Analisis",
        average_level: "Rata-rata Kadar",
        highest: "Tertinggi",
        lowest: "Terendah",
        total_records: "Total Catatan",
        last_status: "Status Terakhir",
        ai_analysis: "Analisis AI",
        condition: "Kondisi",
        recommendation: "Rekomendasi",
        stable: "Stabil",
        needs_monitoring_trend: "Perlu Dipantau",
        healthy_diet: "Pola Makan Sehat",
        trend_ins_insufficient: "Lakukan scan minimal 2 kali untuk melihat perkembangan kesehatan Anda.",
        trend_ins_glucose_high: "Gula darah Anda tinggi (di atas 140 mg/dL). Disarankan untuk membatasi nasi putih, roti, dan minuman manis. Cobalah jalan santai selama 15 menit.",
        trend_ins_glucose_up: "Terjadi kenaikan gula darah dari data sebelumnya. Periksa kembali apakah Anda mengonsumsi makanan manis berlebih akhir-akhir ini.",
        trend_ins_glucose_down: "Bagus! Gula darah Anda menunjukkan penurunan yang sehat. Pertahankan pola makan saat ini.",
        trend_ins_glucose_stable: "Kadar gula darah Anda stabil dan terkontrol dengan baik. Terus jaga pola hidup sehat Anda.",
        trend_ins_hb_low: "Hb Anda rendah (Anemia). Anda mungkin merasa mudah lelah atau pusing. Perbanyak makan bayam, hati ayam, atau daging merah.",
        trend_ins_hb_ideal: "Hb Anda berada di angka yang sangat ideal. Oksigen dalam darah Anda tersalurkan dengan sempurna ke seluruh tubuh.",
        trend_ins_hb_normal: "Kadar Hemoglobin Anda normal. Tetap konsumsi nutrisi seimbang untuk menjaga energi Anda.",
        trend_ins_chol_high: "Kolesterol Anda cukup tinggi. Batasi makanan gorengan dan bersantan. Perbanyak konsumsi buah dan sayuran segar.",
        trend_ins_chol_normal: "Kadar kolesterol Anda terpantau aman. Ini sangat baik untuk kesehatan jantung dan pembuluh darah Anda.",
        
        // Scan Page
        smart_ingestion: "Pemasukan Pintar",
        analysis_complete: "Analisis Selesai",
        ai_interpretation_ready: "Interpretasi AI Siap",
        upload_medical_reports: "Unggah laporan medis untuk analisis AI",
        select_medical_file: "Pilih berkas medis",
        file_types_supported: "Mendukung berkas PDF, JPG dan PNG hingga 10MB",
        select_file_btn: "Pilih Berkas",
        ai_engine_status: "Status Mesin AI",
        openrouter_active: "OPENROUTER AKTIF",
        take_photo_btn: "AMBIL FOTO",
        import_pdf_btn: "IMPOR PDF",
        auto_redacting: "Menyensor Info Pasien Otomatis",
        analyzing_document: "Menganalisis Dokumen",
        progress: "Kemajuan",
        key_metrics_found: "Metrik Kunci Ditemukan",
        verify_edit_warning: "* Harap verifikasi dan edit angka yang salah sebelum menyimpan.",
        no_standard_metrics_detected: "Tidak ada metrik standar yang terdeteksi.",
        clinical_interpretation: "Interpretasi Klinis",
        save_to_dashboard_btn: "Simpan ke Dasbor",
        saving: "Menyimpan...",
        ocr_error: "Gagal menganalisis dokumen. Periksa API Key OpenRouter Anda.",
        save_failed: "Gagal menyimpan.",
        
        // Profile Page
        app_settings: "Pengaturan Aplikasi",
        appearance: "Tampilan",
        dark_mode: "Mode Gelap Antigravity",
        light_mode: "Mode Terang Klinis",
        delete_account: "Hapus Akun",
        contact_support: "Hubungi Dukungan untuk Penonaktifan",
        personal_data: "Data Pribadi",
        fullname_identifier: "Nama Lengkap (Pengenal)",
        registered_email: "Email Terdaftar",
        account_uid: "UID Akun",
        privacy_security: "Privasi & Keamanan",
        auth_mechanism: "Mekanisme Autentikasi",
        last_active: "Terakhir Aktif (Masuk)",
        sign_out_from_account: "Keluar dari Akun",
        health_passport: "Paspor Kesehatan",
        institution: "Institusi",
        total_records_profile: "Total Catatan",
        verification: "Verifikasi",
        verified: "TERVERIFIKASI",
        unverified: "BELUM VERIFIKASI",
        stability: "Stabilitas",
        joined: "Bergabung",
        language: "Bahasa Aplikasi",
        choose_language: "Pilih Bahasa",
    },
    en: {
        // App Name
        app_name: "LabView AI",
        
        // Navigation / Tabs
        nav_home: "Home",
        nav_history: "History",
        nav_trends: "Trends",
        nav_profile: "Profile",
        
        // Login Page
        login_title: "LabView AI",
        login_subtitle: "Medical Transformation Platform",
        email_address: "Email Address",
        password: "Password",
        reset: "Reset",
        authenticate: "Authenticate",
        social_integration: "Social Integration",
        continue_with_google: "Continue with Google",
        unregistered: "UNREGISTERED?",
        register_now: "Register Now",
        login_failed: "Login Failed: Double check your email and password.",
        google_login_failed: "Google Sign-In failed: ",
        
        // Register Page
        join_labview: "Join LabView",
        establish_digital_identity: "Establish your digital identity",
        health_profile: "Health Profile",
        personalize_metrics: "Personalize your metrics",
        full_identity: "Full Identity",
        secret_code: "Secret Code (Password)",
        continue_btn: "CONTINUE",
        biological_sex: "Biological Sex",
        male: "Male",
        female: "Female",
        primary_goal: "Primary Goal",
        monitor_health: "Monitor Health",
        manage_condition: "Manage Condition",
        fitness_tracking: "Fitness Tracking",
        finalize_profile: "FINALIZE PROFILE",
        initializing: "INITIALIZING...",
        quick_setup: "Quick Setup",
        import_google_profile: "Import Google Profile",
        already_have_access: "ALREADY HAVE ACCESS?",
        login_here: "Login Here",
        registration_failed: "Registration Failed: ",
        
        // Dashboard Page
        system_active: "System Active",
        app_guide: "App Guide",
        tutorial_step_1_title: "Scan Report",
        tutorial_step_1_desc: "Take a picture of your lab result paper.",
        tutorial_step_2_title: "Track Score",
        tutorial_step_2_desc: "The higher the number, the better.",
        tutorial_step_3_title: "Meds Reminder",
        tutorial_step_3_desc: "The app alerts you when it's time to take your medication.",
        understood: "Understood",
        system_health_index: "System Health Index",
        no_data: "No Data",
        optimal: "Optimal",
        diagnostic_link: "Diagnostic Link",
        processed_files: "Processed {count} file(s)",
        add_med: "Add Medication",
        scans_total: "Scans Total",
        blood_sugar: "Blood Sugar",
        medical_schedule: "Medical Schedule",
        no_schedule_found: "No Schedule Found",
        confirm_delete_med: "Delete this medication schedule?",
        medication_alert: "Medication Alert!",
        time_to_take_med: "Time to take your medicine:",
        i_have_taken_it: "I HAVE TAKEN IT",
        recent_alerts: "Recent Alerts",
        attention_required: "Attention Required",
        no_new_notifications: "No New Notifications",
        save_btn: "Save",
        
        // Detail Page
        decrypting_report: "Decrypting Report",
        ai_diagnostic: "AI Diagnostic",
        system_analytics: "SYSTEM ANALYTICS",
        optimal_condition: "Optimal Condition",
        optimal_condition_msg: "All lab results look good. Maintain your healthy lifestyle!",
        needs_monitoring: "Needs Monitoring",
        needs_monitoring_msg: "Results slightly out of range. Just manage your diet and get enough rest.",
        extra_attention: "Extra Attention Required",
        extra_attention_msg: "Some results require doctor consultation. Stay calm, this is just an early precaution.",
        health_assistant: "Health Assistant",
        export_for_doctor: "Export for Doctor",
        consult_telemed: "Consult Telemed",
        chat_welcome: "Hello! Do you have any questions about this lab result?",
        ai_analyzing: "AI ANALYZING...",
        ask_lab_placeholder: "Ask about lab results...",
        ai_busy_error: "Sorry, AI connection is busy.",
        check_further: "Check Further",
        attention: "Attention",
        no_interpretation: "No interpretation provided by AI model.",
        
        // History Page
        retrieving_archives: "RETRIEVING ARCHIVES...",
        history_archive: "History Archive",
        medical_records_timeline: "Medical Records Timeline",
        search_placeholder: "Search interpretation or date...",
        no_archival_records_found: "No Archival Records Found",
        all: "All",
        normal: "Normal",
        watch: "Watch",
        alert: "Alert",
        
        // Trends Page
        accessing_database: "Accessing Database...",
        health_intel: "Health Intel",
        analytics: "Analytics",
        average_level: "Average Level",
        highest: "Highest",
        lowest: "Lowest",
        total_records: "Total Records",
        last_status: "Last Status",
        ai_analysis: "AI Analysis",
        condition: "Condition",
        recommendation: "Recommendation",
        stable: "Stable",
        needs_monitoring_trend: "Needs Monitoring",
        healthy_diet: "Healthy Diet",
        trend_ins_insufficient: "Perform at least 2 scans to track your health progress.",
        trend_ins_glucose_high: "Your blood sugar is high (above 140 mg/dL). It is recommended to limit white rice, bread, and sugary drinks. Try a 15-minute light walk.",
        trend_ins_glucose_up: "There is an increase in blood sugar from the previous record. Check if you have consumed excess sweets lately.",
        trend_ins_glucose_down: "Great! Your blood sugar shows a healthy decrease. Maintain your current diet.",
        trend_ins_glucose_stable: "Your blood sugar levels are stable and well controlled. Keep maintaining a healthy lifestyle.",
        trend_ins_hb_low: "Your Hb is low (Anemia). You might feel tired or dizzy easily. Eat more spinach, chicken liver, or red meat.",
        trend_ins_hb_ideal: "Your Hb is at an ideal range. Oxygen in your blood is distributed perfectly throughout your body.",
        trend_ins_hb_normal: "Your Hemoglobin level is normal. Keep consuming balanced nutrients to maintain your energy.",
        trend_ins_chol_high: "Your cholesterol is quite high. Limit fried and coconut milk foods. Increase consumption of fresh fruits and vegetables.",
        trend_ins_chol_normal: "Your cholesterol level is safe. This is very good for your heart and blood vessels.",
        
        // Scan Page
        smart_ingestion: "Smart Ingestion",
        analysis_complete: "Analysis Complete",
        ai_interpretation_ready: "AI Interpretation Ready",
        upload_medical_reports: "Upload medical reports for AI analysis",
        select_medical_file: "Select medical file",
        file_types_supported: "Supports PDF, JPG and PNG files up to 10MB",
        select_file_btn: "Select File",
        ai_engine_status: "AI Engine Status",
        openrouter_active: "OPENROUTER ACTIVE",
        take_photo_btn: "TAKE PHOTO",
        import_pdf_btn: "IMPORT PDF",
        auto_redacting: "Auto-Redacting Patient Info",
        analyzing_document: "Analyzing Document",
        progress: "Progress",
        key_metrics_found: "Key Metrics Found",
        verify_edit_warning: "* Please verify and edit incorrect numbers before saving.",
        no_standard_metrics_detected: "No standard metrics detected.",
        clinical_interpretation: "Clinical Interpretation",
        save_to_dashboard_btn: "Save to Dashboard",
        saving: "Saving...",
        ocr_error: "Failed to analyze document. Check your OpenRouter API Key.",
        save_failed: "Failed to save.",
        
        // Profile Page
        app_settings: "App Settings",
        appearance: "Appearance",
        dark_mode: "Antigravity Dark Mode",
        light_mode: "Clinical Light Mode",
        delete_account: "Delete Account",
        contact_support: "Contact Support for Deactivation",
        personal_data: "Personal Data",
        fullname_identifier: "Full Name (Identifier)",
        registered_email: "Registered Email",
        account_uid: "Account UID",
        privacy_security: "Privacy & Security",
        auth_mechanism: "Auth Mechanism",
        last_active: "Last Active (Sign In)",
        sign_out_from_account: "Sign Out From Account",
        health_passport: "Health Passport",
        institution: "Institution",
        total_records_profile: "Total Records",
        verification: "Verification",
        verified: "VERIFIED",
        unverified: "UNVERIFIED",
        stability: "Stability",
        joined: "Joined",
        language: "App Language",
        choose_language: "Choose Language",
    }
};

export function LanguageProvider({ children }) {
    const [language, setLanguage] = useState(() => {
        return localStorage.getItem('app_lang') || 'id';
    });

    useEffect(() => {
        localStorage.setItem('app_lang', language);
    }, [language]);

    const t = (key, params = {}) => {
        let text = translations[language]?.[key] || translations['id']?.[key] || key;
        Object.entries(params).forEach(([k, v]) => {
            text = text.replace(`{${k}}`, v);
        });
        return text;
    };

    const changeLanguage = (lang) => {
        setLanguage(lang);
    };

    return (
        <LanguageContext.Provider value={{ language, t, changeLanguage }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    return useContext(LanguageContext);
}
